# Generated by Django 4.1.3 on 2022-12-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercontactnumber', models.CharField(max_length=15, null=True)),
                ('useraddress', models.CharField(max_length=200, null=True)),
                ('usercity', models.CharField(max_length=100, null=True)),
                ('userstate', models.CharField(max_length=100, null=True)),
                ('userregdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerconnectionid', models.CharField(max_length=10, null=True)),
                ('customerconnectiontype', models.CharField(max_length=100, null=True)),
                ('customerconnectionstartdate', models.DateField(null=True)),
                ('customeroccupation', models.CharField(max_length=100, null=True)),
                ('customerconnectionload', models.CharField(max_length=100, null=True)),
                ('customerplotno', models.CharField(max_length=50, null=True)),
                ('customercity', models.CharField(max_length=100, null=True)),
                ('customerpincode', models.CharField(max_length=10, null=True)),
                ('customeraddress', models.CharField(max_length=200, null=True)),
                ('customerstate', models.CharField(max_length=100, null=True)),
                ('customerdescription', models.CharField(max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billformonth', models.CharField(max_length=50, null=True)),
                ('currentreading', models.CharField(max_length=50, null=True)),
                ('previousreading', models.CharField(max_length=50, null=True)),
                ('totalunit', models.CharField(max_length=100, null=True)),
                ('chargeperunit', models.CharField(max_length=100, null=True)),
                ('finalamount', models.CharField(max_length=100, null=True)),
                ('duedate', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.connection')),
            ],
        ),
    ]
