# Generated by Django 4.1.3 on 2022-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='chargeperunit',
            new_name='dayelectricitychargeperunit',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='currentreading',
            new_name='dayelectricitycurrentreading',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='previousreading',
            new_name='dayelectricitypreviousreading',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='totalunit',
            new_name='dayelectricitytotalunit',
        ),
        migrations.AddField(
            model_name='bill',
            name='gaschargeperunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='gascurrentreading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='gaspreviousreading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='gastotalunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='nightelectricitychargeperunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='nightelectricitycurrentreading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='nightelectricitypreviousreading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='nightelectricitytotalunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='standingcharge',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
